services:
  # 1. The Web Service (My Django ALX travel app)
  - type: web
    name: alx-travel-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn alx_travel_app.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - fromGroup: alx-travel-app-env

  # 2. The Redis instance (for Celery)
  - type: redis
    name: celery-broker
    ipAllowList: []

  # 3. The Background Worker (for Celery)
  - type: worker
    name: celery-worker
    env: python
    startCommand: "celery -A alx_travel_app worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - fromGroup: alx-travel-app-env

  # 4. The Database (PostgreSQL)
  - type: postgres
    name: alx-travel-app-db
    ipAllowList: []

# Shared Environment Variables for all services
envVarGroups:
  - name: alx-travel-app-env
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: alx-travel-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: celery-broker
          property: connectionString
