databases:
  - name: alx-travel-app-db
    plan: free # Explicitly use the free plan for the database

services:
  - type: redis
    name: celery-broker
    plan: free # Explicitly use the free plan for Redis

  - type: web
    name: alx-travel-app
    env: python
    plan: free # ADDED: Explicitly set the web service to the free plan
    buildCommand: "./build.sh"
    startCommand: "gunicorn alx_travel_app.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: celery-broker
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    plan: free # ADDED: Explicitly set the worker to the free plan
    startCommand: "celery -A alx_travel_app worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATABASE_URL
        fromDatabase:
          name: alx-travel-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: celery-broker
          property: connectionString
